### ISSUE TITLE
will there be a reject version of ex3?

### ISSUE THREAD

**Issue by avereyishere** [HackerN64/F3DEX3#20]

**Comment by sauraen** [comment]
Probably not. The main benefit of a reject microcode is a larger vertex buffer, usually about double the normal size, so for EX3 it would hold over 100 vertices. But EX3 already has a 56 vertex buffer; T3D (the homebrew microcode) has 70, and its developer found minimal performance gains from increasing the size from 56 to 64 to 70. Basically the larger buffer only helps when you have way more vertices than the buffer size which all use the same material. So if you were regularly drawing objects with 500 verts all with the same material, then moving from 56 to >100 verts in the buffer would probably make it go a little faster. But this is pretty rare in N64 games. The future "mesh compiler" I'm hoping to make, which would be used during fast64 export, would also mostly eliminate this gain, causing the RSP processing to be nearly as fast with a smaller vertex buffer as a larger one.

The only reason it's not a "100% no" is because it's not too hard of a change to make to the microcode, so there's a chance I'd do it in a couple years just for fun.
